# Pre-commit configuration.
# https://pre-commit.com

# pre-commit install
# pre-commit run --all-files

default_install_hook_types:
  - pre-push
  - pre-commit

default_stages:
  - pre-commit

repos:
  # Fix some errors with Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.2
    hooks:
      - id: ruff
        args: [ --fix, --exit-zero, --show-fixes ]
        name: "ruff: fixing"
      - id: ruff-format
        name: "ruff: formatting"

  # Lint Python files with Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.2
    hooks:
      - id: ruff
        name: "ruff: linting"

  # Check other files
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        stages:
          - pre-commit
          - pre-push
        entry: env DOTENV_PATH="example.env" sh -c "alembic downgrade base && alembic upgrade head && pytest -v"
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
