services:
  api:
    build: InNoHassle-Rooms
    ports:
      - 80
    depends_on:
      migration:
        condition: service_completed_successfully
    env_file: InNoHassle-Rooms/.env
    environment:
      DB_NAME: innohassle_rooms_api
      DB_HOST: db:5432
      DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password

  bot:
    build: InNoHassle-RoomsBot
    depends_on:
      - api
    env_file: InNoHassle-RoomsBot/.env
    environment:
      - API_URL=http://api:80

  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'"]
      start_period: 5s
      interval: 5s
      timeout: 2s
      retries: 3
    environment:
      - POSTGRES_DB=innohassle_rooms_api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password

  migration:
    build: InNoHassle-Rooms
    command: alembic upgrade head
    depends_on:
      db:
        condition: service_healthy
    env_file: InNoHassle-Rooms/.env
    environment:
      DB_NAME: innohassle_rooms_api
      DB_HOST: db:5432
      DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password

secrets:
  db_password:
    file: db_password.txt

volumes:
  db_data:
